apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::767518370874:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HDW2KPGUVWBT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::767518370874:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-13T10:36:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3897"
  uid: bab01398-7ee2-4a15-a4b7-cc374c24e3a1
